== Security System and Access Control using RFID and OpenDevice

The project allows you to run both offline and online.
In Off-line mode, the user can register new keys using the master key, new keys will be saved in the device EEPROM.
On-line mode allows use of a larger number of keys as well as a more intelligent access control.

NOTE: two modes can be used simultaneously

=== Features
 * Online Validation
 * Offline Validation
 * EEPROM Storage
 * Visual and Sounds feedback
 * WiFi connection (tested on ESP8266)

=== Setup 

Install OpenDevice and required libraries

Required Libraries:
 * ESP8266WiFi  (for ESP8266WiFi)
 * MFRC522
 * PubSubClient
 * ArduinoOTA (Optional, if you need remote updates)

NOTE: You must enable the libraries used in: File: "{arduinolibs}/OpenDevice/dependencies.h"               
Check: https://github.com/OpenDevice/opendevice-lib-arduino/issues/6

== Tutorial and Schematics

https://opendevice.atlassian.net/wiki/display/DOC/Access+Control+using+RFID

== Video

* https://www.youtube.com/watch?v=ulyDsupaZsU
* https://youtu.be/ElfcVBrfEXk


