== opendevice-lib-arduino

This library is responsible for communication using the API and protocols supported by OpenDevice.

link:https://github.com/OpenDevice/OpenDevice/wiki/Supported-Devices[See supported devices]

=== Example

```
#include <ESP8266WiFi.h>  // Enable ESP8266 Embedded
#include <OpenDevice.h>

const char* ssid = "--";
const char* password = "--";

void setup() {
  ODev.name("ODev-Thing1");
  ODev.enableDebug();

  ODev.addDevice("LED", 2, Device::DIGITAL);

  WiFi.mode(WIFI_AP_STA);
  WiFi.begin(ssid, password);
  ODev.begin(WiFi);
}

void loop() {
  ODev.loop();
}

``` 

See complete examples and projects in **examples** folder

== What is OpenDevice?

OpenDevice is a set of tools and APIs to build solutions for the *"Internet of Things"* like home automations systems, robotics, smart city, energy monitoring, security, sensor monitoring. +
Provide an open and unified framework to interconnect IoT devices, data, and applications over the Web,
if you need communication between software and hardware, probably your place is here.

The main objective is monitor and control inexpensive hardwares like *Arduino, RaspberryPI and similar platforms*, local(offline) or over the *cloud* using high-level programing languages and with abstraction of protocols and low-level details.

This allows you to focus on your project and innovation, leave obscure details of communication protocols and specifications with OpenDevice, you will make a major step towards the success of your project.

TIP: Plug your device (Arduino/Raspberypi/Other) to the Cloud and sync in real-time	

=== Dependencies

**You must enable the libraries used in**: "{arduinolibs}/OpenDevice/dependencies.h" 

Please note that the OpenDevice also requires some other libraries to function properly, when used with other connection types or sensors, like the library for the Enc28j60 chip.      

The dependencies are not mandatory, only if you want to use other features as (IR or the ENC28J60 module, etc ..)


== Install

This library is available through the Arduino library manager

See: link:http://www.arduino.cc/en/guide/libraries[Installing Additional Arduino Libraries]


== Docs

See documentation and examples at:

http://opendevice.io

https://opendevice.atlassian.net/wiki/display/DOC/Getting+started

